//! Layout of the `#[repr(C)]` structs shared with .NET, pinned in `abi-layout.json`.
//!
//! The compiler computes offsets and sizes here and the .NET tests (src/Rustino.NET.Tests)
//! compare `Marshal.OffsetOf`/`Marshal.SizeOf` of the matching .NET structs with the same
//! snapshot, so both sides are checked against one truth. After an intentional change:
//!
//!     UPDATE_ABI_SNAPSHOT=1 cargo test --release abi_layout

use std::fmt::Write as _;
use std::mem::{align_of, offset_of, size_of};
use std::path::{Path, PathBuf};

struct FieldLayout {
    name: &'static str,
    offset: usize,
    size: usize,
    align: usize,
}

struct StructLayout {
    name: &'static str,
    size: usize,
    align: usize,
    fields: Vec<FieldLayout>,
}

fn field_layout<S, T>(_field: impl Fn(&S) -> &T) -> (usize, usize) {
    (size_of::<T>(), align_of::<T>())
}

/// `struct_layout!(path::To::Struct { field_a, field_b })` lists every field in declaration
/// order. The exhaustive pattern makes the build fail when a field is added to the struct and
/// not here; the test checks that the listed order matches the offsets.
macro_rules! struct_layout {
    ($($seg:ident)::+ { $($field:ident),* $(,)? }) => {{
        type S = $($seg)::+;
        #[allow(dead_code)]
        fn exhaustive(value: &S) {
            let S { $($field: _),* } = value;
        }
        StructLayout {
            name: last_segment(stringify!($($seg)::+)),
            size: size_of::<S>(),
            align: align_of::<S>(),
            fields: vec![$({
                let (size, align) = field_layout(|s: &S| &s.$field);
                FieldLayout {
                    name: stringify!($field),
                    offset: offset_of!(S, $field),
                    size,
                    align,
                }
            }),*],
        }
    }};
}

fn last_segment(path: &'static str) -> &'static str {
    path.rsplit("::").next().unwrap_or(path).trim()
}

/// Every `#[repr(C)]` struct that crosses the FFI boundary.
fn layouts() -> Vec<StructLayout> {
    vec![struct_layout!(crate::config::RustinoInitParams {
        title,
        icon_file,
        width,
        height,
        center_on_initialize,
        use_os_default_size,
        resizable,
        topmost,
        devtools_enabled,
        clipboard_enabled,
        ignore_certificate_errors,
        web_security_enabled,
        log_verbosity,
        log_callback,
        log_context,
        about_name,
        about_version,
        about_copyright,
        about_website,
        about_license,
        about_authors,
        about_comments,
    })]
}

fn render(layouts: &[StructLayout]) -> String {
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str(
        "  \"_comment\": \"Generated by `UPDATE_ABI_SNAPSHOT=1 cargo test abi_layout` (src/abi_layout.rs); \
         checked by the Rust and .NET interop tests. Do not edit by hand.\",\n",
    );
    let _ = writeln!(out, "  \"pointer_width\": {},", usize::BITS);
    out.push_str("  \"structs\": [\n");
    for (i, layout) in layouts.iter().enumerate() {
        out.push_str("    {\n");
        let _ = writeln!(out, "      \"name\": \"{}\",", layout.name);
        let _ = writeln!(out, "      \"size\": {},", layout.size);
        let _ = writeln!(out, "      \"align\": {},", layout.align);
        out.push_str("      \"fields\": [\n");
        for (j, field) in layout.fields.iter().enumerate() {
            let _ = writeln!(
                out,
                "        {{ \"name\": \"{}\", \"offset\": {}, \"size\": {}, \"align\": {} }}{}",
                field.name,
                field.offset,
                field.size,
                field.align,
                if j + 1 < layout.fields.len() { "," } else { "" }
            );
        }
        out.push_str("      ]\n");
        let _ = writeln!(out, "    }}{}", if i + 1 < layouts.len() { "," } else { "" });
    }
    out.push_str("  ]\n}\n");
    out
}

fn snapshot_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("abi-layout.json")
}

fn rust_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            rust_files(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            out.push(path);
        }
    }
}

/// Names of the structs marked `#[repr(C...)]` in src/ (a plain line scan: attributes are
/// expected on their own line, as rustfmt writes them).
fn repr_c_structs_in_source() -> Vec<(String, String)> {
    let mut files = Vec::new();
    rust_files(&Path::new(env!("CARGO_MANIFEST_DIR")).join("src"), &mut files);
    let mut found = Vec::new();
    for file in files {
        let text = std::fs::read_to_string(&file).unwrap_or_default();
        let mut pending = false;
        for line in text.lines().map(str::trim) {
            if line.starts_with("#[repr(C") {
                pending = true;
            } else if pending && line.starts_with("#[") {
                continue;
            } else if pending {
                let words: Vec<&str> = line.split(|c: char| !c.is_alphanumeric() && c != '_').collect();
                if let Some(i) = words.iter().position(|w| *w == "struct") {
                    if let Some(name) = words.get(i + 1) {
                        found.push((name.to_string(), file.display().to_string()));
                    }
                }
                pending = false;
            }
        }
    }
    found
}

#[test]
fn listed_fields_follow_declaration_order() {
    for layout in layouts() {
        for pair in layout.fields.windows(2) {
            assert!(
                pair[0].offset < pair[1].offset,
                "{}: field `{}` is listed after `{}` but declared before it; list the fields of \
                 struct_layout! in declaration order",
                layout.name,
                pair[1].name,
                pair[0].name
            );
        }
    }
}

#[test]
fn every_repr_c_struct_is_listed() {
    let listed: Vec<&str> = layouts().iter().map(|l| l.name).collect();
    let missing: Vec<String> = repr_c_structs_in_source()
        .into_iter()
        .filter(|(name, _)| !listed.contains(&name.as_str()))
        .map(|(name, file)| format!("{name} ({file})"))
        .collect();
    assert!(
        missing.is_empty(),
        "#[repr(C)] structs missing from layouts() in src/abi_layout.rs: {}. Add them, then run \
         UPDATE_ABI_SNAPSHOT=1 cargo test --release abi_layout",
        missing.join(", ")
    );
}

#[test]
fn layout_matches_snapshot() {
    let expected = render(&layouts());
    let path = snapshot_path();
    if std::env::var_os("UPDATE_ABI_SNAPSHOT").is_some() {
        std::fs::write(&path, &expected).expect("cannot write abi-layout.json");
        return;
    }
    if usize::BITS != 64 {
        // The snapshot pins the layout of the 64-bit targets Rustino ships for
        eprintln!("abi_layout: snapshot comparison skipped on a {}-bit target", usize::BITS);
        return;
    }
    let actual = std::fs::read_to_string(&path).unwrap_or_default().replace("\r\n", "\n");
    if actual == expected {
        return;
    }
    let diff: Vec<String> = expected
        .lines()
        .zip(actual.lines().chain(std::iter::repeat("<missing>")))
        .filter(|(e, a)| e != a)
        .map(|(e, a)| format!("  expected: {}\n  snapshot: {}", e.trim(), a.trim()))
        .collect();
    panic!(
        "The #[repr(C)] layout differs from {} (a change of the FFI structs must be mirrored in \
         the .NET structs):\n{}\nIf the change is intentional, run UPDATE_ABI_SNAPSHOT=1 cargo \
         test --release abi_layout and update the .NET side.",
        path.display(),
        if diff.is_empty() { "  (snapshot has extra lines)".to_string() } else { diff.join("\n") }
    );
}
